#!/usr/bin/env python3

import roslib
import rospy

from hmi_agent_node.main import HmiAgentNode

NODE_NAME = 'hmi_agent_node'
roslib.load_manifest(NODE_NAME)

if __name__ == '__main__':
    rospy.init_node(NODE_NAME)
    try:
        node = HmiAgentNode()
    except rospy.ROSInterruptException:
        pass